/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MEBRunmu6Fc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Judson } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Component() {
  return (
    (<div
      className="flex flex-col min-h-[100dvh] bg-gradient-to-b from-[#0072C6] to-[#D00000]">
      <header className="px-4 lg:px-6 h-14 flex items-center justify-between">
        <Link className="flex items-center justify-center" href="#">
          <CupSodaIcon className="h-8 w-8 text-white" />
          
          <span className="sr-only">Pepsi</span>
        </Link>
        <nav className="flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium text-white hover:underline underline-offset-4"
            href="#">
            Products
          </Link>
          <Link
            className="text-sm font-medium text-white hover:underline underline-offset-4"
            href="#">
            About
          </Link>
        </nav>
      </header>
      <main className="flex-1">
      <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_550px] lg:gap-12 xl:grid-cols-[1fr_650px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-4xl font-bold tracking-tighter text-white sm:text-6xl xl:text-7xl/none">
                    Refreshing the World, One Sip at a Time.
                  </h1>
                  <p className="max-w-[600px] text-white md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    Discover the iconic taste of Pepsi, a refreshing beverage that has been quenching thirst for generations.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-[#D00000] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#D00000]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#D00000] disabled:pointer-events-none disabled:opacity-50"
                    href="#">
                    Shop Now
                  </Link>
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 border-white bg-transparent px-8 text-sm font-medium text-white shadow-sm transition-colors hover:bg-white hover:text-[#0072C6] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-white disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800"
                    href="#">
                    Learn More
                  </Link>
                </div>
              </div>
              <div className="lg:col-start-2 lg:col-end-3 flex justify-center lg:justify-end">
                <img
                  alt="Pepsi"
                  className="mx-auto lg:ml-auto overflow-hidden rounded-xl object-cover object-center sm:w-full object-contain"
                  src="/pepsi.png"
                />
              </div>
            </div>
          </div>
        </section>

        <section className="w-full py-12 md:py-24 lg:py-32 bg-white">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <img
                alt="Pepsi Can"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="550"
                src="/placeholder.svg"
                width="550" />
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2
                    className="text-3xl font-bold tracking-tighter text-[#0072C6] sm:text-5xl">
                    Iconic Taste, Refreshing Experience
                  </h2>
                  <p
                    className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                    Pepsi's signature blend of cola, caramel, and citrus flavors has been delighting taste buds for
                    generations. Enjoy the refreshing and iconic taste of Pepsi.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-[#0072C6] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#0072C6]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#0072C6] disabled:pointer-events-none disabled:opacity-50"
                    href="#">
                    Explore Products
                  </Link>
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 border-[#0072C6] bg-transparent px-8 text-sm font-medium text-[#0072C6] shadow-sm transition-colors hover:bg-[#0072C6] hover:text-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#0072C6] disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800"
                    href="#">
                    Learn More
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-gradient-to-b from-[#0072C6] to-[#D00000]">
          <div
            className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
            <div className="space-y-2">
              <h2
                className="text-3xl font-bold tracking-tighter text-white md:text-4xl/tight">
                Discover the Refreshing Variety of Pepsi
              </h2>
              <p
                className="max-w-[600px] text-white md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                From classic Pepsi to exciting new flavors, explore the wide range of Pepsi products that cater to every
                taste.
              </p>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <img
                alt="Pepsi Zero"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
                height="300"
                src="/placeholder.svg"
                width="300" />
              <img
                alt="Pepsi Wild Cherry"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
                height="300"
                src="/placeholder.svg"
                width="300" />
              <img
                alt="Pepsi Blue"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
                height="300"
                src="/placeholder.svg"
                width="300" />
              <img
                alt="Pepsi Mango"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
                height="300"
                src="/placeholder.svg"
                width="300" />
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t border-white/20">
        <p className="text-xs text-white/70">© 2024 Pepsi. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-xs text-white/70 hover:underline underline-offset-4"
            href="#">
            Terms of Service
          </Link>
          <Link
            className="text-xs text-white/70 hover:underline underline-offset-4"
            href="#">
            Privacy
          </Link>
        </nav>
        <Link
            className="inline-flex h-10 items-center justify-center rounded-md bg-[#D00000] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#D00000]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#D00000] disabled:pointer-events-none disabled:opacity-50"
            href="#">
            Super Offer - 99% Off
          </Link>
      </footer>
    </div>)
  );
}

function CupSodaIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 8 1.75 12.28a2 2 0 0 0 2 1.72h4.54a2 2 0 0 0 2-1.72L18 8" />
      <path d="M5 8h14" />
      <path d="M7 15a6.47 6.47 0 0 1 5 0 6.47 6.47 0 0 0 5 0" />
      <path d="m12 8 1-6h2" />
    </svg>)
  );
}
